import * as vscode from 'vscode';
import { BridgeSnapshot, ProjectContext } from './types';
export class AssistantView implements vscode.WebviewViewProvider, vscode.Disposable { private view?:vscode.WebviewView; private state?:BridgeSnapshot; private context?:ProjectContext; private disposables:vscode.Disposable[]=[];
  constructor(private readonly extensionUri:vscode.Uri){ }
  resolveWebviewView(view:vscode.WebviewView){this.view=view;view.webview.options={enableScripts:true,localResourceRoots:[this.extensionUri]};view.webview.html=this.html(view.webview);this.disposables.push(view.webview.onDidReceiveMessage(m=>this.onMessage?.(m)));this.render();}
  onMessage?: (message:any)=>void;
  setSnapshot(s:BridgeSnapshot){this.state=s;this.render();} setContext(c:ProjectContext){this.context=c;this.render();}
  private render(){if(!this.view)return;this.view.webview.postMessage({type:'state',snapshot:this.state,context:this.context});}
  private html(w:vscode.Webview){const nonce=String(Date.now()); return `<!doctype html><html><head><meta charset="UTF-8"><style>body{font:13px var(--vscode-font-family);color:var(--vscode-foreground);padding:12px}.pill{padding:3px 7px;border-radius:10px;background:var(--vscode-badge-background)}pre{white-space:pre-wrap;max-height:180px;overflow:auto}.muted{opacity:.7}button{color:inherit;background:var(--vscode-button-background);border:0;padding:5px;margin-top:8px}input{color:inherit;background:var(--vscode-input-background);border:1px solid var(--vscode-input-border);padding:5px;width:75%}</style></head><body><h3>JARVIS</h3><div id="status" class="pill">Checking bridge…</div><p id="task" class="muted">No active task reported.</p><div><input id="chat" placeholder="Send a command to JARVIS"/><button id="send">Send</button></div><h4>Agents</h4><pre id="agents">No agents reported.</pre><h4>Recent events</h4><pre id="events">No events reported.</pre><h4>Diagnostics</h4><pre id="diag">No diagnostics.</pre><button id="refresh">Refresh</button><script nonce="${nonce}">const vscode=acquireVsCodeApi();const e=id=>document.getElementById(id);document.getElementById('refresh').onclick=()=>vscode.postMessage({type:'refresh'});document.getElementById('send').onclick=()=>{const i=e('chat');if(i.value.trim()){vscode.postMessage({type:'command',text:i.value.trim()});i.value=''}};window.addEventListener('message',ev=>{const d=ev.data,s=d.snapshot||{},j=s.state||{},jar=j.jarvis||{};e('status').textContent=s.status==='online'?'Online':s.status==='offline'?'Offline: '+(s.lastError||'bridge unavailable'):'Checking bridge…';e('task').textContent=jar.active_task?'Active task: '+jar.active_task:'No active task reported.';e('agents').textContent=JSON.stringify(j.agents||[],null,2);e('events').textContent=JSON.stringify(j.events||[],null,2);e('diag').textContent=JSON.stringify((d.context||{}).diagnostics||[],null,2)});</script></body></html>`;}
  dispose(){this.disposables.forEach(d=>d.dispose());}
}
